// Generated by https://quicktype.io

export interface Stay {
  city: string
  country: string
  superHost: boolean
  title: string
  rating: number
  maxGuests: number
  type: string
  beds: number | null
  photo: string
}

export enum Type {
  EntireApartment = 'Entire apartment',
  EntireHouse = 'Entire house',
  PrivateRoom = 'Private room'
}
